name: Deploy HTML CV to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger action on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build HTML (example step)
        run: echo "Building HTML"  # Can be your custom build step

      - name: Run Tests (optional step)
        run: echo "Running Tests"  # Can be your custom test step

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Path to directory you want to deploy, e.g., root
