name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - master  # or 'main', based on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.Git_Token }}
          publish_dir: .  # Set to '.' if index.html is in root
